//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WORK.Models
{
    using System;
    using System.Collections.Generic;

    // partial class  兩個同名的(AccountBook)partial class 會被視為同一個有要新增欄位可以用
    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        public int Categoryyy { get; set; }
        public int Amounttt { get; set; }
        public System.DateTime Dateee { get; set; }
        public string Remarkkk { get; set; }
    }
}
